language: java
jdk: openjdk11
env:
  global:
  - secure: GNXohVyIu3iSbosz5vmDoE0w3DssKiApgwrMbr1NpLNZMP+hwulJQfcaPpbq9Hrs7sXFeIPke8A4+wCI25L9TsFanre0QOEG0Y8obYiiQvSc1wv5M9BLSRAdUbf+olPzKnVjzmxMGr+eAyhV8I6Qupv7NRhkXaSOAD4qSs1+9P2AiqcZipQUZ3ZC6Czuzwp9eII0xPh8IawF3GNbCosI+wu7NX2wdlLNN9jK8H8fD8Hj2/SYIxwgGLmJ6PzaEHfkoSlCQO+tgYJaXq4dESdrrzNuFkw5h+XL3LVh9fiLpNFn7GwWPlUtgEjFfK2qi6LmKRFTLpXzCC0qMUI+RDpA8CwXAaeFdyifLn6yUbQShIYEUDDUnLJf8uMu+cJ57tOp1UKaYyqzuaTy/fO8Nj4snMTl3Q3ykI3E1j3Fny8K0BE9FD2Gh/Mn0EPzL/vxOiKY9tDpKX6Hp5+g2XHTL3j1cTck1f60vcyRVRpASFqms7+X30Aeb+aJNVKnP1L2Tnpvozrh+cn67HIXP16Vh2X2GDMizIHNGXNwBH5iWDwFkfVbc/IVTEmwoZD5f7lvvwmYk8ifKY8zM66NwXXosPQ5RFJQhMvqMBSygiY8xJ1Em1aV8iAicCkdS0O9UJEQKXnVn8vO31Je2BU3pBJUa5A+C3FSm/l0hB9jovja/A5r9lQ=
  - secure: zsYWCmeb34B8ABHMdDHrDXI4JvVKzKz0Wt1YpfeIfBNP9cgioXGAoRoDWi0XFEjXIApkamkgjxCfncu99G0TnWrmJH8ubwqcPO+Fell35GuLnJ8//LLQR5yxOXaz1yfcChf1u7qbzypZQUIfXGW0IK3fZ4erlScbnvkFfytaGdrOh9NnCyHyt9WDj7wumCaKvtl52z1A5KOYRBsE0C1SZXPyNVMBopvKVXgxNDcTxLjnBmsBxbJlCHZElSP13ApBKz3VfmLRdASs3bmbYgK/SdKFd+HdU9Gkf7KrkHcaQJJTvTwm6+QAAgyONDksuQ6ci5Pym/8szNRJHkULqfQTpFvkMuh0DjztcXRlqARZ5jDydNZH1QTpWaAw/lyvC1LrFVl+hXh86gKyubt0WvBItTjs9tQ0miDNw1ycAwSVbnRyvBKPh1qMxmytSQFW7ATxSrcx6WTZjUCrxo2zMXg+7oXXfUwgcljoCuypirvZHAAuAwsXOgG7iu4m7njIniYFKzUDEhupcVQV4Qdc16o/1FCE5NSy9fu5vfzoGIjbS/O3ePj3Nh6P3PHmyNxHm4b71+ayaHMY6xz+A/UV+mlwjXOIq1f4z7NcmiWhJCp1GaTk59xzl1q8fJydKVeGYAAbQCJwLi79WP/N++YxEdgZtIaSY55PdVUso0N0YZqh2Io=
install: skip
script: mvn --settings .mvn/settings.xml install && ([[ $TRAVIS_BRANCH != "master" ]] || mvn --settings .mvn/settings.xml -DskipTests=true deploy)
sudo: false
cache:
  directories: "$HOME/.m2"
branches:
  except: gh-pages
notifications:
  email: joerg.hohwiller@googlemail.com
